<script type="text/javascript">
    $(document).ready(initUnfinalizedCourt);
</script>

<div class="Secondary">
    <div class="inner">
        <div class="clear"></div>
    </div>
</div>
<div>                            
    <div class="clear"></div>
    <div class="login_input" id="contentheader">
        <div id="display_content1" class="main_content">
            <div class="round_top"><div class="round_top_left"></div><div class="round_top_mid"></div><div class="round_top_right"></div><div class="clear"></div></div>
            <table id="specimenTable" cellspacing="0"  class="tableA tableBlowOutPreventer" cellpadding="0" >
                <tr>
                    <th colspan="11" class="grid_heading"><div style="float:left">Specimen Listing</div></th>
                </tr>
                <tr class="bar">        
                    <th style="text-align:left; padding-left:5px;">Specimen ID</th>
                    <th style="text-align:left; padding-left:5px;">Donor First</th>
                    <th style="text-align:left; padding-left:5px;">Donor Last</th>
                    <th style="text-align:left; padding-left:5px;">Received</th>                                            
                </tr>
            </table>
            <div class="round_bottom">
                <div class="round_bottom_left"></div>
                <div class="round_bottom_mid"></div>
                <div class="round_bottom_right"></div>
                <div class="clear"></div>
            </div>  
        </div>
    </div>
</div>