                <div class="top">
                    <div class="top_left"><a href="/specimen.php" style="text-decoration:none;"><img src="images/logo.png" alt="" /></a></div>
                </div>
                <script type="text/javascript">
                    $(document).ready(function() { 
                        $('#btnSubmit').click(function() {
                            var form_data = {
                                email: $('#email').val(),                            
                                ajax: '1'		
                            };
                            $.ajax({
                                url: "/getPassword/do_change_password.php",
                                type: 'POST',
                                data: form_data,
                                success: function(msg) {
                                    if (msg == 'success') {
                                        $.prompt("Password reset instructions sent to given email ", {
                                            buttons: {'Continue': 0 },
                                            focus: 1,
                                            submit:function(e,v,m,f){ 
                                                if(v==0) {
                                                    $.prompt.close(); 
                                                    window.location.assign('/index.php');
                                                }
                                                return false;
                                            }
                                        });
                                    } else {
                                        $.prompt("Given email doesn't exist in our system."+msg, {
                                            buttons: {'Continue': 0 },
                                            focus: 1,
                                            submit:function(e,v,m,f){ 
                                                if(v==0) {
                                                    $.prompt.close(); 
                                                }
                                                return false;
                                            }
                                        });
                                    }
                                }
                            });
                        });
                    
                    
                    });
                    
                </script> 

                <div class="content_wrap" style="padding-bottom:20px;">
                    <div class="content_bg_top"></div>          
                    <form name="frm_pass" id="frm_pass"  action="" method="post" onsubmit="return ValidateElement( 'frm_pass' , 'SelfSubmit' )" > 
                        <div class="content_bg_mid" style="min-height:300px;">
                            <p class="heading_1">Reset Your Password </p>
                            <div class="login_left">&nbsp;</div>
                            <div class="login_right"><div id="message" style="text-align:left;">
                                </div></div>
                            <div class="clear"></div>
                            <div class="login_input">
                                <div class="login_left"><strong>Email address:</strong></div>
                                <div class="login_right"><input type="text" class="login_input_bg" id="email" name="email" value="" /></div>
                                <div class="clear"></div>
                            </div>
                            <div class="login_input"  style="padding-right:267px;" >
                                <button type="submit" value=""  id="btnSubmit" name="btnSubmit" class="submit_btn"><span>Submit</span></button>
                                <div class="clear"></div>
                            </div>                      
                        </div>
                    </form>
                    <div class="content_bg_bottom"></div>