<!DOCTYPE html>
<html>
	<head>
    <title>LABTAB Portal  | [GET NAME]</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">  
    
    <link rel="stylesheet" href="/css/nivo-slider/nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/nivo-slider/themes/default/default.css" type="text/css" media="screen" />
    <link href="/css/jQuery-Impromptu.css" rel="stylesheet" type="text/css" />
    <link href="/css/fileuploader.css" rel="stylesheet" type="text/css" />
		<link href="/css/style.css" rel="stylesheet" type="text/css" />
    <link href="/css/global.css" rel="stylesheet" type="text/css" />
    <link href="/css/jquery.loadmask.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="/css/jquery.ui.datepicker.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery.fancybox-1.3.4.css" media="screen" />

    
    <!--JS Start-->        
    <script type="text/javascript" src="/js/jquery-1.8.1.js"></script>
    <script src="/js/nivo-slider/jquery.nivo.slider.pack.js" type="text/javascript"></script>
    <script type="text/javascript" src="/js/jQuery-Impromptu/jquery-impromptu.js"></script>
    
    <script type="text/javascript" src="/js/fileuploader.js"></script>
    <script type="text/javascript" src="/js/jquery.validate.js"></script>
    <script src="/js/jquery-ui-1.8.js"></script>
    <script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>
    <!-- Load mask -->        
    <script type="text/javascript" src="/js/jquery.loadmask.js"></script>
    <!-- FANCY BOX PLAGINS ADDED HERE -->
    <script type="text/javascript" src="/js/jquery.mousewheel-3.0.4.pack.js"></script>
    <script type="text/javascript" src="/js/jquery.fancybox-1.3.4.pack.js"></script>            
    <!-- MENUE PLAGINS ADDED HERE -->        
    <script src="/js/stuHover.js" type="text/javascript"></script>
		<!-- CUSTOM SCRIPTS -->
    <script type="text/javascript" src="/js/script.js"></script>
    <script type="text/javascript" src="/js/require.js"></script>
    <script type="text/javascript">
    	var email = '<?php echo (isset($_SESSION) && array_key_exists('email', $_SESSION)) ? $_SESSION['email'] : '';?>';
    	<!--  -->
			var full_name = '<?php echo (isset($_SESSION) && array_key_exists('full_name', $_SESSION)) ? $_SESSION['full_name'] : '';?>';
			var seal_condition = '';	
			var seal_org_contacted = '<?php echo \Labtab\Entity\Enum_Seal::SEAL_CONDITION_ORG_CONTACTED; ?>';
			var seal_good = '<?php echo \Labtab\Entity\Enum_Seal::SEAL_CONDITION_GOOD; ?>';
			var seal_bad = '<?php echo \Labtab\Entity\Enum_Seal::SEAL_CONDITION_BAD; ?>'
    	<?php if (property_exists($this, 'number'))
    		echo "var number = " . $this->number . ";"; ?>
    </script>
  </head>
  <body>
      <span class="preload1"></span>
        <span class="preload2"></span>
        <div class="background">
            <div class="main_div" id="dvwait" >
                       
        			<div class="top">
              
              	<div class="top_left"><a href="/specimens.php" style="text-decoration:none;"><img src="/images/logo.png" alt="" /></a></div>
                <div class="top_right">
                  	<?php echo $this->getWelcome(); ?>

                  <div class="clear"></div>
                  <?php echo $this->navDiv(); ?>
                  <div class="clear"></div>
                	
                </div>
								<div class="clear"></div>
               
              </div>
                            
                <div class="content_wrap">
                    <div class="content_bg_top"></div>
                    <div class="content_bg_mid">               


					  					<?php echo $this->listMessages(); ?>
					          	<?php echo $this->layout()->content; ?>

										</div>
					      	<div class="content_bg_bottom"></div>
					      </div>					                
							  <div class = "footer_main">
							    <div class = "footer_left">
								    <p><span>3365 Cypress Mill Road, Suite 9 Brunswick, Georgia 31520 912-265-9277</span></p>
							    </div>
							    <div class = "footer_right"><p><span class = "copy_right" > Copyright & copy;
								    2012 by USAccuscreen, LLC. All Rights Reserved.</span></p>
							    </div>
							    <div class = "clear"></div>
							  </div>
				            
    	</div><!--  main_div -->
    </div><!--  //background -->
</body>
</html>