<script type="text/javascript">
	$(document).ready(initDonors);
</script>

<div class="Secondary">
    <div class="inner">
        <div class="clear"></div>
    </div>
</div>
<div>
    <div >
        <div class="search_top_mid"><div class="search_top_left"></div><div class="search_top_right"></div></div>
        <div class="search_mid_right">
            <div class="search_mid_left">
                <div class="search_mid_body">                      
                    <div class="search_input_div">
                        <strong>Organization</strong>
                        <br>
                        <span id="sp_mywarehouse" class="filter_search_select_m"><select id="labtab_select" name="labtab_select"   >
        <?php
        if ($_SESSION['user_type'] == 'external') {
            echo '<option value="' . $_SESSION['from'] . '" >' . $_SESSION['from'] . '</option>';
        } else {          
					echo '<option value="*" > All Organizations </option>';
          foreach ($this->labtabUsers as $l)
          	echo '<option value="' . $l->getLabtabUsername() . '" > ' . $l->getOrgName() . ' </option>';
        }
        ?>              
                            </select>
                        </span>
                    </div>
                    <div class="search_input_div">
                        <strong>Creation Type</strong>
                        <br>
                        <span id="sp_mywarehouse" class="filter_search_select_m"><select id="creation_select" name="creation_select"   >
        <option value="all" >All</option> 
        <option value="0" >iPad App</option>    
        <option value="1" >Website</option> 
                            </select>
                        </span>
                    </div>
                    <div class="search_input_div"><strong>First Name</strong><br /><span class="filter_search_select_m">
                            <input type="text" name="firstInput" id="firstInput" /></span></div>
                    <div class="search_input_div"><strong>Last Name</strong><br /><span class="filter_search_select_m" id="sp_acfproducts">
                        <input type="text" name="lastInput" id="lastInput"/></div>  
                    <div class="search_input_div"><strong>From</strong><br/>
                        <input readonly="readonly" type="text" id="fromdate" value="01/01/2010" name="fromdate" class="filter_search_input_s" style="border:none;"></div>
                    <div class="search_input_div" style="padding-right:0;"><strong>To</strong><br/>
                        <input readonly="readonly" type="text" id="todate" value="<?php echo date("m/d/Y", time() + 86400); ?>" name="todate" class="filter_search_input_s" style="border:none;"></div>
                    <div class="search_input_div" style="padding-top: 17px;padding-left:291px;float:right">
                        <button type="button" onclick="getDonors();" name="btnCancel" id="btnCancel" value="" class="btnSearch1"><span>Search</span></button> 
                    </div>  
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="search_bottom_mid"><div class="search_bottom_left"></div><div class="search_bottom_right"></div></div>
    </div>
    <div class="clear"></div>
    <div class="login_input" id="contentheader">
        <div id="display_content1" class="main_content">
            <div class="round_top"><div class="round_top_left"></div><div class="round_top_mid"></div><div class="round_top_right"></div><div class="clear"></div></div>
            <table id="userTable" cellspacing="0"  class="tableA tableBlowOutPreventer" cellpadding="0" >
                <tr>
                    <th colspan="11" class="grid_heading"><div style="float:left" id="tableTitle"></div></th>
                </tr>
                <tr class="bar">        
                    <th style="text-align:left; padding-left:5px;">Name</th>
                    <th style="text-align:left; padding-left:5px;">DOB</th>
                    <th style="text-align:left; padding-left:5px;">Phone</th>
                    <th style="text-align:left; padding-left:5px;">Street Address</th>
                    <th style="text-align:left; padding-left:5px;">City</th>
                    <th style="text-align:left; padding-left:5px;">State</th> 
                    <th style="text-align:left; padding-left:5px;">Zip</th>                      
                </tr>
            </table>
            <div class="round_bottom">
                <div class="round_bottom_left"></div>
                <div class="round_bottom_mid"></div>
                <div class="round_bottom_right"></div>
                <div class="clear"></div>
            </div>  
        </div>
    </div>
</div>
